In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.shape

(569, 31)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
# train_test split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [ ]:
# Scaling
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [ ]:
X_train

array([[-0.52580303,  0.79652753, -0.55763818, ..., -0.78042184,
         0.38570459, -0.04739686],
       [-0.6268112 ,  0.49389923, -0.63067181, ..., -0.48076909,
         0.34276842, -0.54032424],
       [ 1.42141005, -0.75235746,  1.40570174, ...,  0.99682356,
        -0.742658  , -1.17673282],
       ...,
       [ 0.08305178,  0.16029323,  0.1074167 , ...,  0.66732988,
        -0.27036011,  0.61793938],
       [-0.30134043, -1.25276646, -0.37281005, ..., -1.21606843,
        -1.31972014, -0.9863888 ],
       [ 2.28559107,  0.13646423,  2.48692593, ...,  2.75774969,
         2.02586635,  0.8701886 ]])

In [ ]:
X_test

array([[ 0.13075008,  0.85371713,  0.18534644, ..., -0.04760924,
        -1.06038567, -0.16252896],
       [ 1.69918252,  1.16111122,  2.11563762, ...,  2.13295507,
         4.40453026,  0.97143542],
       [ 0.26262186,  0.17459063,  0.34487801, ...,  1.52214839,
        -0.07113627, -0.02946171],
       ...,
       [-0.07407204, -0.51645037, -0.03620252, ...,  0.80565505,
         1.29595143,  1.33360976],
       [-0.85969115, -0.47117527, -0.84038851, ..., -0.28633674,
        -0.1638784 ,  1.96423281],
       [-2.00416985, -1.35046536, -1.96078157, ..., -1.76501734,
         0.09717352,  0.63471743]])

In [ ]:
y_train

490    B
415    B
161    M
521    M
313    B
      ..
212    M
547    B
99     M
309    B
108    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
# Label Encoder
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,

In [ ]:
# Numpy array to pytorch
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [ ]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels= labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [ ]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset= CustomDataset(X_test_tensor, y_test_tensor)

In [ ]:
train_dataset[10]

(tensor([ 1.6178,  0.2771,  1.5771,  1.5524,  0.5915,  0.5941,  0.7044,  1.2097,
          0.0188, -0.0653,  0.3361, -0.5828,  0.3636,  0.3762, -0.6644, -0.1154,
         -0.0307,  0.0031, -1.2695, -0.1124,  1.5080, -0.0310,  1.5574,  1.2888,
          0.4489,  0.5480,  0.7621,  0.7419, -0.5606,  0.4924]),
 tensor(1.))

In [ ]:
train_loader= DataLoader(train_dataset, batch_size=32, shuffle= True)
test_loader= DataLoader(test_dataset, batch_size=32, shuffle=True)

In [ ]:
# Defining model
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear =nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out= self.linear(features)
    out= self.sigmoid(out)
    return out

In [ ]:
learning_rate=0.1
epochs=25

In [ ]:
# create model
model= MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loss function
loss_function= nn.BCELoss()

In [ ]:
# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
  print(f'Epoch:{epoch+1},Loss:{loss.item()}')

Epoch:1,Loss:0.029985887929797173
Epoch:2,Loss:0.049446020275354385
Epoch:3,Loss:0.014583386480808258
Epoch:4,Loss:0.022482583299279213
Epoch:5,Loss:0.0011517390375956893
Epoch:6,Loss:0.003630321705713868
Epoch:7,Loss:0.050318218767642975
Epoch:8,Loss:0.015615816228091717
Epoch:9,Loss:0.07121806591749191
Epoch:10,Loss:0.32941341400146484
Epoch:11,Loss:0.022861028090119362
Epoch:12,Loss:0.021503597497940063
Epoch:13,Loss:0.02267455868422985
Epoch:14,Loss:0.004237697459757328
Epoch:15,Loss:0.07428281009197235
Epoch:16,Loss:0.007200282067060471
Epoch:17,Loss:0.0009538308368064463
Epoch:18,Loss:0.10129232704639435
Epoch:19,Loss:0.013381099328398705
Epoch:20,Loss:0.00629178062081337
Epoch:21,Loss:0.009295867756009102
Epoch:22,Loss:0.011779068037867546
Epoch:23,Loss:0.019159948453307152
Epoch:24,Loss:0.03221261128783226
Epoch:25,Loss:0.011244402267038822


In [ ]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features.float())
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9766
